version: "2"

services:
  weather_requests:
    image: mysql:5.7
    volumes: 
      - ./mysql/data/dev:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=weather_requests
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks: 
      - default
    ports: 
      - 3306:3306
    
      
    
    




  
    